- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "Update apt packages"
  become: true
  apt:
    update_cache: true
    force_apt_get: true

- name: "Install Node.js 13"
  shell: |
    # Install Node.js LTS version as our base Node.js version
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs

    # Use n version manager to switch to Node.js v13.8.0
    sudo npm install -g n
    sudo n 13.8.0

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

# - name: "install node exporter."
#   unarchive:
#     src: https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz
#     dest: /tmp
#     remote_src: yes

# - name: "move binary to /usr/local/bin."
#   copy:
#     src: /tmp/node_exporter-0.17.0.linux-amd64/node_exporter
#     dest: /usr/local/bin/node_exporter
#     remote_src: yes
#     mode: "0777"

