---
- name: "Update apt packages"
  apt:
    update_cache: true
    force_apt_get: true

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "Install node and npm"
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present